### PR TITLE
fix: handle the case the ziph does not have preview-gif KVP

### PR DESCRIPTION
**Pull request by billypchan**
## What's new in this PR?

Some Ziph has no value for the key "preview-gif". (Maybe the GIF is small and the preview is not necessary) In that case, return the original image instead.

### CODE REVIEW

**Comment by alexaubry** [comment]
This could slow down the search screen *a lot*. It seems that sometimes Giphy posts don't have a preview because they were uploaded before it was a feature. In this case, the original image would still be a large file.

Therefore, in my opinion, we should not show search results that don't have a preview. GIF search results are not crucial data so there is nothing *really* lost. (what do you think @mikeger?)


I would keep the `previewImage` variable you introduced, and `return images[.preview]`. Then, in `ZiphySearchResultsController` we could add a condition in the `updatePagination` filter to check if this value is not `nil`.

**Comment by mikeger** [comment]
We can keep the property but exclude the images without the preview. Can we change the Giphy query so feed does not contain them? Or should we filter the result when we received it?

**Comment by billypchan** [comment]
After studying some real cases I would suggest checking other size formats with small file sizes before return the original image. e.g.

if no preview image then use fixed_width_downsampled image
if no fixed_width_downsampled then use fixed_width image
if no fixed_width then use downsized image
else use original

**Comment by billypchan** [comment]
@zenkins release minor

**Comment by billypchan** [comment]
@zenkins release minor

**Pull request merged**
